# Numpy
為一個電腦科學或資料科學中很重要的數學運算套件，它可以做很多運算
比較多的時候我們會用它來做許多的矩陣運算，是一個非常方便的套件

In [1]:
# 我們習慣import numpy時縮減成np
# 可以依照你的喜好來選擇要不要縮減(看個人)
import numpy as np

# list與陣列之間的關係

In [2]:
# python語言中有一個重要的資料結構為list
ex_list = [1, 2, 3]
print(ex_list)
"""
他的好處是可以彈性的新增或刪除元素(如果你是資工系的大概就會知道它其實就是linked list)
"""
ex_list.append(4)
print(f"add 4 into list = {ex_list}")
ex_list.remove(2)
print(f"remove 2 from list = {ex_list}")

[1, 2, 3]
add 4 into list = [1, 2, 3, 4]
remove 2 from list = [1, 3, 4]


In [4]:
# numpy中並不是list而是另一個資料型式 稱之為陣列(array)
ex_array = np.array(ex_list) # 這是一個簡單的將list轉換為array的形式
print(ex_array)

[1 3 4]


In [5]:
ex_array = np.array([0.1, 0.3, 0.4]) # 陣列也可以塞入不同的資料型態如浮點數
print(ex_array)

[0.1 0.3 0.4]


In [8]:
ex_array = np.array(
    [
        [0.1, 0.3, 0.4],
        [0.3, 0.8, 0.9]             
    ]
    ) # 而可以是2維陣列
print(ex_array)
print(f"ex_array 的shape為 {ex_array.shape}")

[[0.1 0.3 0.4]
 [0.3 0.8 0.9]]
ex_array 的shape為 (2, 3)


# 矩陣(陣列)運算

In [13]:
# 設定這裡有兩個不同的陣列
# 建立兩個shape相同的陣列
a = np.random.randn(3, 3)
b = np.random.randn(3, 3)
print(f'matrix a = ')
print(a)
print(f'matrix b = ')
print(b)

matrix a = 
[[ 0.81163144  0.37376123  1.26355692]
 [ 1.7294091  -1.70455546 -0.20566204]
 [-1.0964912   0.05989552  0.35963683]]
matrix b = 
[[ 0.38480983  0.38430573  2.01582147]
 [-0.7535114   0.59460429 -0.69470902]
 [-0.92065703 -0.84219661 -0.276701  ]]


In [14]:
# 加減法
print("a + b")
print(a + b)
print("a - b")
print(a - b)

a + b
[[ 1.19644126  0.75806696  3.27937838]
 [ 0.9758977  -1.10995117 -0.90037106]
 [-2.01714823 -0.78230109  0.08293583]]
a - b
[[ 0.42682161 -0.01054451 -0.75226455]
 [ 2.4829205  -2.29915975  0.48904698]
 [-0.17583417  0.90209213  0.63633783]]


In [17]:
# 點積
print("a * b")
print(a * b)

a * b
[[ 0.31232375  0.14363858  2.54710516]
 [-1.30312947 -1.01353599  0.14287527]
 [ 1.00949233 -0.0504438  -0.09951187]]
