# Numpy
為一個電腦科學或資料科學中很重要的數學運算套件，它可以做很多運算
比較多的時候我們會用它來做許多的矩陣運算，是一個非常方便的套件

In [1]:
# 我們習慣import numpy時縮減成np
# 可以依照你的喜好來選擇要不要縮減(看個人)
import numpy as np

# list與陣列之間的關係

In [2]:
# python語言中有一個重要的資料結構為list
ex_list = [1, 2, 3]
print(ex_list)
"""
他的好處是可以彈性的新增或刪除元素(如果你是資工系的大概就會知道它其實就是linked list)
"""
ex_list.append(4)
print(f"add 4 into list = {ex_list}")
ex_list.remove(2)
print(f"remove 2 from list = {ex_list}")

[1, 2, 3]
add 4 into list = [1, 2, 3, 4]
remove 2 from list = [1, 3, 4]


In [3]:
# numpy中並不是list而是另一個資料型式 稱之為陣列(array)
ex_array = np.array(ex_list) # 這是一個簡單的將list轉換為array的形式
print(ex_array)

[1 3 4]


In [4]:
ex_array = np.array([0.1, 0.3, 0.4]) # 陣列也可以塞入不同的資料型態如浮點數
print(ex_array)

[0.1 0.3 0.4]


In [5]:
ex_array = np.array(
    [
        [0.1, 0.3, 0.4],
        [0.3, 0.8, 0.9]             
    ]
    ) # 而可以是2維陣列
print(ex_array)
print(f"ex_array 的shape為 {ex_array.shape}")

[[0.1 0.3 0.4]
 [0.3 0.8 0.9]]
ex_array 的shape為 (2, 3)


# 矩陣(陣列)運算

In [6]:
# 設定這裡有兩個不同的陣列
# 建立兩個shape相同的陣列
a = np.random.randn(3, 3)
b = np.random.randn(3, 3)
print(f'matrix a = ')
print(a)
print(f'matrix b = ')
print(b)

matrix a = 
[[ 0.73375609  0.13663782  0.52406054]
 [-1.32258971 -0.2407907  -0.94848217]
 [ 0.49936171 -0.90213294  0.40845632]]
matrix b = 
[[ 0.43319279 -0.62029645 -0.39044848]
 [-1.04672077  0.29357297 -0.39638695]
 [ 0.08737123 -0.40497012  0.52736527]]


In [7]:
# 加減法
print("a + b")
print(a + b)
print("----------------")
print(np.add(a, b))
print("****************")
print("a - b")
print(a - b)
print("----------------")
print(np.subtract(a, b))

a + b
[[ 1.16694888 -0.48365864  0.13361206]
 [-2.36931048  0.05278227 -1.34486912]
 [ 0.58673294 -1.30710306  0.93582159]]
----------------
[[ 1.16694888 -0.48365864  0.13361206]
 [-2.36931048  0.05278227 -1.34486912]
 [ 0.58673294 -1.30710306  0.93582159]]
****************
a - b
[[ 0.3005633   0.75693427  0.91450902]
 [-0.27586894 -0.53436367 -0.55209521]
 [ 0.41199048 -0.49716282 -0.11890895]]
----------------
[[ 0.3005633   0.75693427  0.91450902]
 [-0.27586894 -0.53436367 -0.55209521]
 [ 0.41199048 -0.49716282 -0.11890895]]


In [8]:
# 元素積 -> 對應的每個元素相乘
print("a * b")
print(a * b)
print("----------------")
print(np.multiply(a, b))

a * b
[[ 0.31785785 -0.08475595 -0.20461864]
 [ 1.38438212 -0.07068964  0.37596596]
 [ 0.04362985  0.36533689  0.21540568]]
----------------
[[ 0.31785785 -0.08475595 -0.20461864]
 [ 1.38438212 -0.07068964  0.37596596]
 [ 0.04362985  0.36533689  0.21540568]]


In [9]:
# 積
"""
dot 這是一個比較危險的函數
官方文件中
如果 a 跟 b 都為1D向量會執行向量內積運算
如果 a 跟 b 都為2D向量會執行會執行矩陣相乘運算
如果 a 或 b 為scalar(純量)會執行一般的相乘
"""
print(a.dot(b))
print("----------------")
print(np.dot(a, b))

[[ 0.22062402 -0.62726199 -0.06428407]
 [-0.40376575  1.13381501  0.11165288]
 [ 1.19628851 -0.74000675  0.37802439]]
----------------
[[ 0.22062402 -0.62726199 -0.06428407]
 [-0.40376575  1.13381501  0.11165288]
 [ 1.19628851 -0.74000675  0.37802439]]


In [10]:
# 矩陣運算
"""
    通常會以@來表示兩個矩陣運算
"""
print("a @ b")
print(a @ b)
print("----------------")
print(np.matmul(a, b))

a @ b
[[ 0.22062402 -0.62726199 -0.06428407]
 [-0.40376575  1.13381501  0.11165288]
 [ 1.19628851 -0.74000675  0.37802439]]
----------------
[[ 0.22062402 -0.62726199 -0.06428407]
 [-0.40376575  1.13381501  0.11165288]
 [ 1.19628851 -0.74000675  0.37802439]]


# Array Shape
陣列中我們常常會使用多個D來表示一個矩陣，在中文的理解上我們會稱之為"軸"，而非"維"

In [11]:
np.random.rand(3) # 1D矩陣

array([0.43404368, 0.81203084, 0.95479611])

In [12]:
np.random.rand(3, 3) # 2D矩陣

array([[0.23548925, 0.12980581, 0.23228351],
       [0.93299835, 0.57964639, 0.69200991],
       [0.61275162, 0.11928007, 0.7316204 ]])

In [13]:
np.random.rand(3, 3, 3) # 3D矩陣

"""
    當然我們可以拓展到多個D來當作ND矩陣
    序列中我們常常用(B, S, D)來當作矩陣 第一軸為Batch、第二軸為Sequence長度而最後一軸為資料特徵的維度
    在影像處理中我們會使用(B, C, H, W)來當作矩陣表示 C為通道(可能為RGB、RGBA或HSV等)、H為高度則W為寬度
    根據不同任務有會有不同的表示方式
"""

array([[[0.49371605, 0.46743574, 0.34742387],
        [0.23331227, 0.9583792 , 0.55786408],
        [0.67602394, 0.23122988, 0.17075648]],

       [[0.55746605, 0.54001778, 0.20353932],
        [0.85484645, 0.07386415, 0.35632017],
        [0.02334093, 0.15378203, 0.28753608]],

       [[0.45108395, 0.05512953, 0.30475985],
        [0.94957494, 0.83732441, 0.87195142],
        [0.70679961, 0.25498838, 0.04001378]]])