In [1]:
import torch
import numpy as np

# Tensor
在深度學習領域中我們常常使用張量(Tensor)來進行矩陣的各種運算，它的好處是可以將資料傳輸到GPU中進行加速運算，與Array的有些許差異

In [2]:
a = torch.tensor([1, 2, 3])
print(a)

tensor([1, 2, 3])


In [3]:
a = torch.rand(size = (3, 3)) # 建立一個3x3的張量
print(a)
print(a.type()) # Float型態的張量

tensor([[0.8315, 0.5504, 0.2540],
        [0.1259, 0.4552, 0.4164],
        [0.4258, 0.7475, 0.3474]])
torch.FloatTensor


In [4]:
a = torch.randint(low=0, high = 100, size = (5,)) # 建立一個長度為5的int型態的張量
print(a)

tensor([49, 87, 87,  0, 82])


In [9]:
# numpy array 轉換 tensor
n_tensor = torch.from_numpy(np.array([1, 2, 3, 4, 5]))
print(n_tensor)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


# Tensor運算

Tensor運算的符號與Array相似，基本的加減乘除外還有內積及元素積

In [5]:
a = torch.rand(size=(5, 5))
b = torch.rand(size=(5, 5))

print(f"a = \n {a}")
print(f"b = \n {b}")

a = 
 tensor([[0.2457, 0.7835, 0.1263, 0.8735, 0.5128],
        [0.8174, 0.5543, 0.3281, 0.8744, 0.8712],
        [0.3942, 0.5331, 0.6542, 0.6771, 0.9121],
        [0.9026, 0.3184, 0.7521, 0.6018, 0.9658],
        [0.7859, 0.4874, 0.4110, 0.3437, 0.7039]])
b = 
 tensor([[0.8097, 0.7062, 0.0140, 0.1258, 0.7216],
        [0.0380, 0.7418, 0.9285, 0.8873, 0.4974],
        [0.8679, 0.5110, 0.0457, 0.0182, 0.8332],
        [0.8103, 0.1843, 0.0901, 0.6698, 0.5979],
        [0.4398, 0.5661, 0.3614, 0.5093, 0.8142]])


In [6]:
# torch.add(a , b)
print(f"a + b \n {a + b}")
# torch.sub(a, b)
# torch.subtract(a, b)
print(f"a - b \n {a - b}")
# torch.mul(a, b)
# torch.multiply(a, b)
print(f"a * b (元素積) \n {a * b}")
# torch.div(a, b)
# torch.divide(a, b)
print(f"a / b \n {a / b}")

a + b 
 tensor([[1.0555, 1.4897, 0.1403, 0.9993, 1.2343],
        [0.8555, 1.2961, 1.2566, 1.7617, 1.3686],
        [1.2621, 1.0441, 0.6999, 0.6953, 1.7453],
        [1.7129, 0.5027, 0.8422, 1.2716, 1.5637],
        [1.2258, 1.0535, 0.7724, 0.8530, 1.5181]])
a - b 
 tensor([[-0.5640,  0.0772,  0.1122,  0.7476, -0.2088],
        [ 0.7794, -0.1875, -0.6004, -0.0129,  0.3738],
        [-0.4737,  0.0221,  0.6084,  0.6589,  0.0789],
        [ 0.0922,  0.1341,  0.6621, -0.0680,  0.3679],
        [ 0.3461, -0.0787,  0.0497, -0.1656, -0.1103]])
a * b (元素積) 
 tensor([[0.1990, 0.5533, 0.0018, 0.1099, 0.3700],
        [0.0311, 0.4112, 0.3046, 0.7758, 0.4334],
        [0.3421, 0.2724, 0.0299, 0.0123, 0.7600],
        [0.7314, 0.0587, 0.0677, 0.4031, 0.5775],
        [0.3457, 0.2759, 0.1485, 0.1750, 0.5731]])
a / b 
 tensor([[ 0.3035,  1.1093,  8.9891,  6.9407,  0.7106],
        [21.4847,  0.7473,  0.3533,  0.9854,  1.7515],
        [ 0.4542,  1.0433, 14.3096, 37.1920,  1.0947],
        [ 1.1138,  

In [7]:
# 矩陣運算
# torch.matmul(a, b)
print(f"a @ b \n {a @ b}")

a @ b 
 tensor([[1.2717, 1.2704, 1.0007, 1.5746, 1.6120],
        [2.0595, 1.8104, 0.9348, 1.6300, 2.3711],
        [1.8570, 1.6492, 0.9210, 1.4526, 2.2421],
        [2.3082, 1.9155, 0.7459, 1.3048, 2.5825],
        [1.5998, 1.5884, 0.7677, 1.1276, 1.9306]])
