In [1]:
import torch
import numpy as np

# Tensor
在深度學習領域中我們常常使用張量(Tensor)來進行矩陣的各種運算，它的好處是可以將資料傳輸到GPU中進行加速運算，與Array的有些許差異

In [2]:
a = torch.tensor([1, 2, 3])
print(a)

tensor([1, 2, 3])


In [3]:
a = torch.rand(size = (3, 3)) # 建立一個3x3的張量
print(a)
print(a.type()) # Float型態的張量

tensor([[0.1971, 0.6213, 0.5077],
        [0.1602, 0.4735, 0.2013],
        [0.7955, 0.6885, 0.5499]])
torch.FloatTensor


In [4]:
a = torch.randint(low=0, high = 100, size = (5,)) # 建立一個長度為5的int型態的張量
print(a)

tensor([90, 81, 95,  4, 84])


In [5]:
# numpy array 轉換 tensor
n_tensor = torch.from_numpy(np.array([1, 2, 3, 4, 5]))
print(n_tensor)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


# Tensor運算

Tensor運算的符號與Array相似，基本的加減乘除外還有內積及元素積

In [6]:
a = torch.rand(size=(5, 5))
b = torch.rand(size=(5, 5))

print(f"a = \n {a}")
print(f"b = \n {b}")

a = 
 tensor([[0.6806, 0.6315, 0.5191, 0.2979, 0.4504],
        [0.4700, 0.7466, 0.9960, 0.1303, 0.2111],
        [0.3581, 0.7986, 0.6293, 0.1265, 0.5862],
        [0.6689, 0.9998, 0.5535, 0.8664, 0.5563],
        [0.5616, 0.1052, 0.4605, 0.4060, 0.1769]])
b = 
 tensor([[0.6820, 0.8668, 0.5778, 0.5491, 0.3688],
        [0.2305, 0.3645, 0.4676, 0.0846, 0.1710],
        [0.7716, 0.7311, 0.1116, 0.9896, 0.2865],
        [0.3848, 0.0189, 0.7552, 0.8264, 0.6874],
        [0.5903, 0.0634, 0.3646, 0.9384, 0.0175]])


In [7]:
# torch.add(a , b)
print(f"a + b \n {a + b}")
# torch.sub(a, b)
# torch.subtract(a, b)
print(f"a - b \n {a - b}")
# torch.mul(a, b)
# torch.multiply(a, b)
print(f"a * b (元素積) \n {a * b}")
# torch.div(a, b)
# torch.divide(a, b)
print(f"a / b \n {a / b}")

a + b 
 tensor([[1.3626, 1.4983, 1.0969, 0.8470, 0.8192],
        [0.7005, 1.1111, 1.4636, 0.2149, 0.3821],
        [1.1297, 1.5297, 0.7409, 1.1160, 0.8727],
        [1.0537, 1.0187, 1.3087, 1.6928, 1.2437],
        [1.1518, 0.1686, 0.8251, 1.3445, 0.1944]])
a - b 
 tensor([[-0.0014, -0.2354, -0.0587, -0.2512,  0.0815],
        [ 0.2395,  0.3821,  0.5283,  0.0457,  0.0401],
        [-0.4135,  0.0675,  0.5177, -0.8631,  0.2998],
        [ 0.2841,  0.9809, -0.2016,  0.0401, -0.1311],
        [-0.0287,  0.0417,  0.0959, -0.5324,  0.1594]])
a * b (元素積) 
 tensor([[0.4642, 0.5474, 0.2999, 0.1636, 0.1661],
        [0.1083, 0.2721, 0.4658, 0.0110, 0.0361],
        [0.2763, 0.5838, 0.0702, 0.1251, 0.1679],
        [0.2574, 0.0189, 0.4180, 0.7160, 0.3824],
        [0.3315, 0.0067, 0.1679, 0.3810, 0.0031]])
a / b 
 tensor([[ 0.9980,  0.7285,  0.8983,  0.5426,  1.2211],
        [ 2.0390,  2.0485,  2.1298,  1.5396,  1.2343],
        [ 0.4641,  1.0924,  5.6396,  0.1278,  2.0464],
        [ 1.7384, 5

In [8]:
# 矩陣運算
# torch.matmul(a, b)
print(f"a @ b \n {a @ b}")

a @ b 
 tensor([[1.3907, 1.2338, 1.1357, 1.6097, 0.7204],
        [1.4358, 1.4235, 0.9072, 1.6126, 0.6796],
        [1.3086, 1.1011, 0.9598, 1.5416, 0.5461],
        [1.7755, 1.4006, 1.7729, 2.2377, 1.1816],
        [1.0232, 0.8807, 0.7962, 1.2745, 0.6392]])
