In [1]:
import numpy as np
import torch as th

c:\Users\Wen2Tee5\Desktop\Postgraduate\torchPlayGround\torchEnv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# PPMI 計算方式

In [2]:
sample = np.random.randint(0, 10, size = (5, 5))
print(sample)

[[1 4 1 3 5]
 [5 5 3 8 7]
 [1 0 9 2 2]
 [5 6 4 7 8]
 [7 4 2 1 2]]


In [3]:
print((sample==0).sum(axis = 1) != 0) # 0 在window中的出現
print((sample==1).sum(axis = 1) != 0) # 1 在window中的出現次數
print((((sample==0).sum(axis = 1) != 0) & ((sample==1).sum(axis = 1) != 0))) # 0跟1 在window中共同出現

[False False  True False False]
[ True False  True False  True]
[False False  True False False]


In [4]:
# PPMI 公式
numDoc = len(sample)
p0 = ((sample==0).sum(axis = 1) != 0).sum().astype(np.float32) /  numDoc
p1 = ((sample==1).sum(axis = 1) != 0).sum().astype(np.float32) /  numDoc
p01 = (((sample==0).sum(axis = 1) != 0) & ((sample==1).sum(axis = 1) != 0)).sum() / numDoc

In [5]:
print(f'p0 = {p0}')
print(f'p1 = {p1}')
print(f'p01 = {p01}')
print(f'PPMI = {np.log(np.exp(p01 / p0 * p1))}')

p0 = 0.2
p1 = 0.6
p01 = 0.2
PPMI = 0.6


# 平均數_變異數

In [6]:
MIN = 0.
MAX = 10.

In [7]:
sample = (MAX - MIN) * np.random.ranf(size=(10,100)) + MIN

In [8]:
sample

array([[9.78710739e-01, 4.51188004e+00, 3.31799990e+00, 1.11875248e-01,
        7.06937271e+00, 1.30746491e+00, 4.52028875e+00, 6.53180726e+00,
        9.19933847e+00, 5.60783159e+00, 8.33535711e+00, 1.84923229e+00,
        2.98672459e+00, 1.60444646e+00, 4.51957534e+00, 3.85452295e+00,
        1.34283957e+00, 7.85838745e-01, 9.59557255e+00, 7.36502483e+00,
        4.58378966e+00, 6.49191029e-01, 7.17468024e+00, 8.09338776e+00,
        8.37453786e+00, 6.51445445e+00, 2.62635325e+00, 7.18698205e+00,
        1.24831327e+00, 3.32109325e+00, 1.18470250e+00, 7.60011393e+00,
        9.97606387e-01, 3.02970577e+00, 3.97712119e+00, 9.90286467e+00,
        7.95983868e+00, 7.32033808e+00, 6.29935855e+00, 1.81892148e+00,
        9.05168278e+00, 6.21948285e+00, 1.34109587e+00, 2.97315660e+00,
        3.93938737e+00, 2.94657131e+00, 4.08429990e+00, 5.08045491e+00,
        2.58780310e-01, 5.37512490e+00, 5.46221669e-01, 1.11143771e+00,
        2.84363232e+00, 1.85584434e+00, 9.65172362e-01, 8.509879

In [9]:
mean = sample.mean(axis=0)
std = sample.std(axis=0)

In [10]:
(sample - mean) / std

array([[-1.23671330e+00,  6.40163284e-01, -4.39664290e-01,
        -1.95048817e+00,  5.54960500e-01, -1.22780649e+00,
        -3.63457798e-01,  1.46321717e-01,  1.08313190e+00,
         7.56429508e-01,  1.17531894e+00, -1.34841861e+00,
        -4.93880187e-01, -1.51058719e+00, -4.31439913e-01,
        -6.23629193e-01, -1.18898315e+00, -1.27865603e+00,
         1.14310040e+00,  9.36347444e-01,  4.46177967e-01,
        -1.41907525e+00,  9.29568380e-01,  1.35264373e+00,
         1.32819890e+00,  5.96851974e-01, -1.31490233e+00,
         7.28854944e-02, -9.46883692e-01, -4.08899435e-01,
        -9.43269243e-01,  9.90448406e-01, -8.81745782e-01,
        -3.18225347e-01,  4.32979626e-02,  1.22735641e+00,
         1.25677531e+00,  1.06116019e+00,  3.72199587e-01,
        -1.12454611e+00,  9.46272702e-01,  2.28665130e-01,
        -1.31703771e+00, -5.90448853e-01, -6.28560450e-01,
        -1.25474584e+00, -2.56212263e-02,  1.51319086e-02,
        -1.00092270e+00,  7.39908398e-01, -1.06319278e+0

In [11]:
time_step = np.random.ranf(size=(100, 20, 80))

In [12]:
print(time_step.shape)

(100, 20, 80)


In [13]:
spilit = 0.8
spilit_index = int(time_step.shape[1] * 0.8)

In [14]:
print(time_step[:,spilit_index:].shape)
print(time_step[:,:spilit_index].shape)

(100, 4, 80)
(100, 16, 80)


In [15]:
x = np.random.randint(low = 1 , high = 10, size=(3))
y = np.random.randint(low = 1 , high = 10, size=(3, 3))

In [16]:
x

array([6, 2, 6])

In [17]:
y

array([[3, 8, 2],
       [1, 1, 2],
       [7, 6, 3]])

# 使用np.dot時要特別注意
dot 在某些狀況下會等於矩陣相乘，如果使用不當會導致錯誤的計算

In [18]:
np.dot(x, y)

array([62, 86, 34])

In [19]:
x @ y

array([62, 86, 34])

In [20]:
np.matmul(x, y)

array([62, 86, 34])

In [21]:
(y ** 2)

array([[ 9, 64,  4],
       [ 1,  1,  4],
       [49, 36,  9]])

In [22]:
np.sqrt((x ** 2).sum())

8.717797887081348

In [23]:
np.sqrt((y ** 2).sum(axis = 1))

array([8.77496439, 2.44948974, 9.69535971])

In [24]:
np.sqrt((x ** 2).sum()) * np.sqrt((y ** 2).sum(axis = 1))

array([76.498366  , 21.3541565 , 84.52218644])

In [25]:
print((x @ y.T) / (np.sqrt((x ** 2).sum()) * np.sqrt((y ** 2).sum(axis = 1))))

[0.60132003 0.93658581 0.85184734]
