In [268]:
import numpy as np

# PPMI 計算方式

In [269]:
sample = np.random.randint(0, 10, size = (5, 5))
print(sample)

[[4 5 0 9 2]
 [6 2 6 3 2]
 [6 9 2 4 1]
 [5 6 0 0 6]
 [1 6 3 9 1]]


In [270]:
print((sample==0).sum(axis = 1) != 0) # 0 在window中的出現
print((sample==1).sum(axis = 1) != 0) # 1 在window中的出現次數
print((((sample==0).sum(axis = 1) != 0) & ((sample==1).sum(axis = 1) != 0))) # 0跟1 在window中共同出現

[ True False False  True False]
[False False  True False  True]
[False False False False False]


In [271]:
# PPMI 公式
numDoc = len(sample)
p0 = ((sample==0).sum(axis = 1) != 0).sum().astype(np.float32) /  numDoc
p1 = ((sample==1).sum(axis = 1) != 0).sum().astype(np.float32) /  numDoc
p01 = (((sample==0).sum(axis = 1) != 0) & ((sample==1).sum(axis = 1) != 0)).sum() / numDoc

In [272]:
print(f'p0 = {p0}')
print(f'p1 = {p1}')
print(f'p01 = {p01}')
print(f'PPMI = {np.log(np.exp(p01 / p0 * p1))}')

p0 = 0.4
p1 = 0.4
p01 = 0.0
PPMI = 0.0
