In [1]:
import numpy as np

# PPMI 計算方式

In [2]:
sample = np.random.randint(0, 10, size = (5, 5))
print(sample)

[[7 3 5 2 9]
 [1 3 1 7 7]
 [0 4 5 1 8]
 [0 4 2 1 3]
 [0 9 9 1 0]]


In [3]:
print((sample==0).sum(axis = 1) != 0) # 0 在window中的出現
print((sample==1).sum(axis = 1) != 0) # 1 在window中的出現次數
print((((sample==0).sum(axis = 1) != 0) & ((sample==1).sum(axis = 1) != 0))) # 0跟1 在window中共同出現

[False False  True  True  True]
[False  True  True  True  True]
[False False  True  True  True]


In [4]:
# PPMI 公式
numDoc = len(sample)
p0 = ((sample==0).sum(axis = 1) != 0).sum().astype(np.float32) /  numDoc
p1 = ((sample==1).sum(axis = 1) != 0).sum().astype(np.float32) /  numDoc
p01 = (((sample==0).sum(axis = 1) != 0) & ((sample==1).sum(axis = 1) != 0)).sum() / numDoc

In [5]:
print(f'p0 = {p0}')
print(f'p1 = {p1}')
print(f'p01 = {p01}')
print(f'PPMI = {np.log(np.exp(p01 / p0 * p1))}')

p0 = 0.6
p1 = 0.8
p01 = 0.6
PPMI = 0.8000000000000002


# 平均數_變異數

In [6]:
MIN = 0.
MAX = 10.

In [7]:
sample = (MAX - MIN) * np.random.ranf(size=(10,100)) + MIN

In [8]:
sample

array([[8.86094206e+00, 4.51029849e+00, 9.74491947e-01, 9.81179829e+00,
        1.69895539e+00, 3.63296849e+00, 9.47856423e+00, 5.59935687e+00,
        3.66436809e+00, 1.27719136e+00, 7.61549508e+00, 6.78489315e+00,
        9.75247734e+00, 8.33101752e+00, 3.20553312e+00, 4.49696214e+00,
        4.17818114e+00, 5.58921455e+00, 7.96407700e-01, 7.54901549e+00,
        7.46561362e+00, 7.56146872e+00, 8.90426424e+00, 4.67705126e+00,
        4.04501609e-01, 9.07628885e+00, 9.22637819e+00, 1.64135556e+00,
        2.76544664e+00, 7.12153186e+00, 5.48614313e+00, 2.52891836e+00,
        9.86255651e+00, 9.49154090e+00, 2.64187131e+00, 7.23954918e+00,
        2.13962088e+00, 7.72367007e+00, 1.74229947e+00, 2.20865388e-01,
        8.66391085e+00, 6.23015541e+00, 1.77511812e+00, 5.01290219e+00,
        2.92678163e+00, 3.23414613e-01, 4.27436006e+00, 6.82455397e+00,
        1.22235253e-01, 5.68828341e+00, 6.90791277e+00, 7.10114217e+00,
        2.76593216e+00, 2.65302082e+00, 7.87402716e+00, 5.066422

In [9]:
mean = sample.mean(axis=0)
std = sample.std(axis=0)

In [10]:
(sample - mean) / std

array([[ 1.87615484e+00, -6.21798517e-01, -1.40460404e+00,
         1.83952463e+00, -7.88951663e-01, -2.58702944e-01,
         1.97891614e+00,  3.08308433e-03, -9.98871653e-01,
        -1.02939198e+00,  8.87371173e-01, -5.84874691e-02,
         1.26545437e+00,  1.70733285e+00, -5.09307605e-01,
        -2.93901529e-01,  5.00791913e-03, -2.95302198e-01,
        -2.38292116e+00,  6.23440792e-01,  4.97468072e-01,
         1.12873440e+00,  1.07876042e+00,  9.50212435e-01,
        -1.63899369e+00,  9.87525035e-01,  1.13080621e+00,
        -1.04974937e+00, -1.91306729e-01,  6.75683332e-01,
        -4.83809740e-02, -6.87647185e-01,  1.52388748e+00,
         1.02869624e+00, -8.50041372e-01,  3.11263049e-01,
        -8.91193891e-01,  1.00997807e+00, -1.13690132e+00,
        -1.53022727e+00,  1.52851655e+00,  2.30667806e-01,
        -8.16403946e-01, -8.20189410e-02, -6.75864230e-01,
        -1.20019162e+00, -4.62876512e-01, -9.50316195e-03,
        -1.52378611e+00, -1.63325007e-01,  4.08378479e-0

In [11]:
time_step = np.random.ranf(size=(100, 20, 80))

In [12]:
print(time_step.shape)

(100, 20, 80)


In [13]:
spilit = 0.8
spilit_index = int(time_step.shape[1] * 0.8)

In [18]:
print(time_step[:,spilit_index:].shape)
print(time_step[:,:spilit_index].shape)

(100, 4, 80)
(100, 16, 80)
