In [12]:
import numpy as np

# PPMI 計算方式

In [13]:
sample = np.random.randint(0, 10, size = (5, 5))
print(sample)

[[6 9 4 3 2]
 [4 6 2 4 3]
 [7 6 1 0 5]
 [8 8 8 4 0]
 [4 0 8 7 1]]


In [14]:
print((sample==0).sum(axis = 1) != 0) # 0 在window中的出現
print((sample==1).sum(axis = 1) != 0) # 1 在window中的出現次數
print((((sample==0).sum(axis = 1) != 0) & ((sample==1).sum(axis = 1) != 0))) # 0跟1 在window中共同出現

[False False  True  True  True]
[False False  True False  True]
[False False  True False  True]


In [15]:
# PPMI 公式
numDoc = len(sample)
p0 = ((sample==0).sum(axis = 1) != 0).sum().astype(np.float32) /  numDoc
p1 = ((sample==1).sum(axis = 1) != 0).sum().astype(np.float32) /  numDoc
p01 = (((sample==0).sum(axis = 1) != 0) & ((sample==1).sum(axis = 1) != 0)).sum() / numDoc

In [16]:
print(f'p0 = {p0}')
print(f'p1 = {p1}')
print(f'p01 = {p01}')
print(f'PPMI = {np.log(np.exp(p01 / p0 * p1))}')

p0 = 0.6
p1 = 0.4
p01 = 0.4
PPMI = 0.2666666666666667


# 平均數_變異數

In [17]:
MIN = 0.
MAX = 10.

In [18]:
sample = (MAX - MIN) * np.random.ranf(size=(10,100)) + MIN

In [19]:
sample

array([[1.76271992e+00, 4.68345313e-01, 4.59512519e+00, 4.21255005e+00,
        7.48516127e+00, 3.24257159e+00, 9.73598671e+00, 8.93987985e+00,
        1.19428922e+00, 2.87351844e+00, 2.22442810e+00, 8.11986134e+00,
        7.54209211e+00, 4.57687833e+00, 5.16473233e+00, 9.89574534e+00,
        5.20871762e-01, 1.95126554e+00, 3.28142412e+00, 5.12485297e+00,
        8.18830187e+00, 3.93210676e+00, 2.72156840e+00, 3.55341095e+00,
        1.77630083e+00, 1.93555889e+00, 3.00242327e+00, 4.26040296e+00,
        4.47754327e+00, 9.52632563e+00, 5.91751931e+00, 4.36244096e+00,
        6.03074240e+00, 4.13336232e+00, 7.56316529e+00, 5.79884231e+00,
        9.92915849e+00, 7.07140544e+00, 4.02669854e+00, 7.71308228e+00,
        9.46904466e+00, 6.58011371e+00, 5.06045417e+00, 7.94844767e+00,
        9.88960561e+00, 8.57232867e+00, 6.12521191e+00, 1.38597291e+00,
        3.03243404e+00, 5.17479108e+00, 3.30553792e+00, 7.94862727e+00,
        9.49212807e+00, 3.64984260e+00, 1.91764335e+00, 8.836573

In [20]:
mean = sample.mean(axis=0)
std = sample.std(axis=0)

In [21]:
(sample - mean) / std

array([[-8.34724025e-01, -1.75501839e+00,  5.05046751e-02,
        -1.82822048e-01,  1.77751562e+00, -6.33846794e-01,
         1.01537365e+00,  1.22066086e+00, -9.50212032e-01,
        -4.73410601e-01, -8.25551117e-01,  4.29561717e-01,
         1.57770291e-02,  1.06753503e-01,  1.99980438e-01,
         1.22290998e+00, -1.12191348e+00, -5.84514720e-01,
        -6.66494821e-01,  1.87231748e-02,  8.50393055e-01,
        -1.02290940e+00, -7.33267419e-01, -4.68746180e-01,
        -9.50715140e-01, -1.65464592e+00, -8.79587275e-01,
        -4.99126664e-01, -8.23815894e-01,  1.08463044e+00,
        -1.09554170e-01, -1.09208804e-01,  1.25180422e-01,
        -5.39185940e-01,  6.89191135e-01,  3.61158843e-01,
         1.78933516e+00,  6.22114526e-01, -9.14035481e-01,
         1.69588715e+00,  1.55000385e+00, -3.74198201e-01,
        -1.44936891e-01,  9.80249275e-01,  1.42661221e+00,
         1.25326736e+00,  8.88751986e-01, -1.42251306e+00,
        -1.55802698e+00,  4.11277719e-01, -7.23405998e-0