In [1]:
import torch

c:\Users\Wen2Tee5\Desktop\Postgraduate\torchPlayGround\torchEnv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
data = torch.randn(size=(2,3,4), dtype=torch.float32)

In [4]:
print(data)
print(data.shape)

tensor([[[ 1.3041, -1.4468,  1.5431,  2.3896],
         [ 0.0697, -0.6828, -0.6796, -0.2833],
         [-1.0599, -2.3791, -1.0157, -0.7794]],

        [[-0.2726,  0.9455, -0.8711,  1.0805],
         [ 1.0938, -0.2665,  0.1050, -1.0835],
         [ 0.4180, -0.8421, -1.1483, -2.2453]]])
torch.Size([2, 3, 4])


In [7]:
perdata = data.permute(0,2,1)

In [8]:
print(perdata)
print(perdata.shape)

tensor([[[ 1.3041,  0.0697, -1.0599],
         [-1.4468, -0.6828, -2.3791],
         [ 1.5431, -0.6796, -1.0157],
         [ 2.3896, -0.2833, -0.7794]],

        [[-0.2726,  1.0938,  0.4180],
         [ 0.9455, -0.2665, -0.8421],
         [-0.8711,  0.1050, -1.1483],
         [ 1.0805, -1.0835, -2.2453]]])
torch.Size([2, 4, 3])


In [9]:
perdata.permute(0,2,1)

tensor([[[ 1.3041, -1.4468,  1.5431,  2.3896],
         [ 0.0697, -0.6828, -0.6796, -0.2833],
         [-1.0599, -2.3791, -1.0157, -0.7794]],

        [[-0.2726,  0.9455, -0.8711,  1.0805],
         [ 1.0938, -0.2665,  0.1050, -1.0835],
         [ 0.4180, -0.8421, -1.1483, -2.2453]]])