In [20]:
import dgl
import torch

# u,v的表示方式

他是透過element wise的方式來連結 比如A矩陣中的第一個元素對應到B矩陣的第一個元素來做連結<br>

In [21]:
u, v = torch.tensor([0, 0, 0, 1]), torch.tensor([1, 2, 3, 3])

In [22]:
g = dgl.graph((u, v))

In [23]:
print(g)

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})


In [24]:
g = dgl.graph((u, v), num_nodes = 10)

# 得知所有有參與節點的連接狀況以及有參與edge Id

In [25]:
g.edges(form='all')

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3]))

In [26]:
g.edges(form='eid')

tensor([0, 1, 2, 3])

In [27]:
g.add_edges(u=1, v=9)

In [28]:
g.edges()

(tensor([0, 0, 0, 1, 1]), tensor([1, 2, 3, 3, 9]))

In [29]:
g.ndata['x'] = torch.ones(g.num_nodes(), 3)

In [30]:
g.edata['x'] = torch.ones(g.num_edges(), dtype=torch.int32)

In [31]:
adj = g.adjacency_matrix()

In [32]:
g = dgl.graph(data=([0],[1]))

In [33]:
g.adjacency_matrix()

tensor(indices=tensor([[0],
                       [1]]),
       values=tensor([1.]),
       size=(2, 2), nnz=1, layout=torch.sparse_coo)