In [1]:
import torch
import dgl
import dgl.function as fn

c:\Users\Wen2Tee5\Desktop\Postgraduate\torchPlayGround\torchEnv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
g = dgl.DGLGraph()
g.add_edges([0, 0], [1, 2])

c:\Users\Wen2Tee5\Desktop\Postgraduate\torchPlayGround\torchEnv\lib\site-packages\dgl\heterograph.py:72: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning('Recommend creating graphs by `dgl.graph(data)`'


In [3]:
g.ndata['x'] = torch.rand((3, 5))

In [4]:
g.ndata['x']

tensor([[0.6846, 0.1935, 0.9030, 0.3972, 0.1158],
        [0.0810, 0.7738, 0.8180, 0.8777, 0.8443],
        [0.5936, 0.7259, 0.8995, 0.5028, 0.9399]])

In [5]:
g.edata['w'] = torch.tensor([0.1, 0.1],dtype = torch.float32)

In [6]:
g.update_all(fn.u_mul_e('x','w','m'), fn.sum('m','h'))

In [7]:
g.ndata['x']

tensor([[0.6846, 0.1935, 0.9030, 0.3972, 0.1158],
        [0.0810, 0.7738, 0.8180, 0.8777, 0.8443],
        [0.5936, 0.7259, 0.8995, 0.5028, 0.9399]])

In [8]:
g.ndata['h']

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0685, 0.0193, 0.0903, 0.0397, 0.0116],
        [0.0685, 0.0193, 0.0903, 0.0397, 0.0116]])

In [9]:
g2 = dgl.DGLGraph()
g2.add_edges([1, 2], [0, 0])

In [10]:
g2.ndata['x'] = torch.rand((3, 5))

In [11]:
g2.edata['w'] = torch.tensor([0.1, 0.1],dtype = torch.float32)

In [12]:
g2.update_all(fn.u_mul_e('x','w','m'), fn.sum('m','h'))

In [13]:
g2.ndata['x']

tensor([[0.3126, 0.6933, 0.9906, 0.4060, 0.6519],
        [0.4326, 0.3516, 0.0173, 0.0036, 0.2730],
        [0.7200, 0.5517, 0.0577, 0.5017, 0.0256]])

In [14]:
g2.ndata['h']

tensor([[0.1153, 0.0903, 0.0075, 0.0505, 0.0299],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

In [15]:
g2.update_all(fn.u_mul_e('x','w','m'), fn.mean('m','mean_h'))

In [16]:
g2.ndata['mean_h']

tensor([[0.0576, 0.0452, 0.0038, 0.0253, 0.0149],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

In [47]:
g2 = dgl.DGLGraph()
g2.add_edges([0,0,0], [1,1,1])

c:\Users\Wen2Tee5\Desktop\Postgraduate\torchPlayGround\torchEnv\lib\site-packages\dgl\heterograph.py:72: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning('Recommend creating graphs by `dgl.graph(data)`'


In [48]:
g2.ndata['x'] = torch.rand((2, 5))

In [49]:
g2.edata['w'] = torch.tensor([1.,1.,1.],dtype = torch.float32)

In [50]:
g2.update_all(fn.u_mul_e('x','w','m'), fn.mean('m','h'))

In [51]:
g2.ndata['x']

tensor([[0.0247, 0.4774, 0.6240, 0.6862, 0.4852],
        [0.2859, 0.4954, 0.8469, 0.3482, 0.6814]])

In [52]:
g2.ndata['h']

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0247, 0.4774, 0.6240, 0.6862, 0.4852]])