In [1]:
import torch
import dgl
import dgl.function as fn

c:\Users\Wen2Tee5\Desktop\Postgraduate\torchPlayGround\torchEnv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
g = dgl.DGLGraph()
g.add_edges([0, 0], [1, 2])

c:\Users\Wen2Tee5\Desktop\Postgraduate\torchPlayGround\torchEnv\lib\site-packages\dgl\heterograph.py:72: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning('Recommend creating graphs by `dgl.graph(data)`'


In [3]:
g.ndata['x'] = torch.rand((3, 5))

In [4]:
g.ndata['x']

tensor([[0.0370, 0.2525, 0.5587, 0.8078, 0.6461],
        [0.7988, 0.5723, 0.4634, 0.5455, 0.7065],
        [0.0593, 0.6434, 0.7757, 0.2264, 0.0371]])

In [5]:
g.edata['w'] = torch.tensor([0.1, 0.1],dtype = torch.float32)

In [6]:
g.update_all(fn.u_mul_e('x','w','m'), fn.sum('m','h'))

In [7]:
g.ndata['x']

tensor([[0.0370, 0.2525, 0.5587, 0.8078, 0.6461],
        [0.7988, 0.5723, 0.4634, 0.5455, 0.7065],
        [0.0593, 0.6434, 0.7757, 0.2264, 0.0371]])

In [8]:
g.ndata['h']

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0037, 0.0252, 0.0559, 0.0808, 0.0646],
        [0.0037, 0.0252, 0.0559, 0.0808, 0.0646]])

In [9]:
g2 = dgl.DGLGraph()
g2.add_edges([1, 2], [0, 0])

In [10]:
g2.ndata['x'] = torch.rand((3, 5))

In [11]:
g2.edata['w'] = torch.tensor([0.1, 0.1],dtype = torch.float32)

In [12]:
g2.update_all(fn.u_mul_e('x','w','m'), fn.sum('m','h'))

In [13]:
g2.ndata['x']

tensor([[0.0947, 0.5051, 0.6092, 0.2985, 0.3849],
        [0.3265, 0.0965, 0.7144, 0.5445, 0.9315],
        [0.2543, 0.4968, 0.7429, 0.8066, 0.0014]])

In [14]:
g2.ndata['h']

tensor([[0.0581, 0.0593, 0.1457, 0.1351, 0.0933],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

In [15]:
g2.update_all(fn.u_mul_e('x','w','m'), fn.mean('m','mean_h'))

In [16]:
g2.ndata['mean_h']

tensor([[0.0290, 0.0297, 0.0729, 0.0676, 0.0466],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

In [17]:
g2 = dgl.DGLGraph()
g2.add_edges([0,0,0], [1,1,1])

In [18]:
g2.ndata['x'] = torch.rand((2, 5))

In [19]:
g2.edata['w'] = torch.tensor([1.,1.,1.],dtype = torch.float32)

In [20]:
g2.update_all(fn.u_mul_e('x','w','m'), fn.mean('m','h'))

In [21]:
g2.ndata['x']

tensor([[0.9370, 0.8509, 0.3196, 0.1809, 0.7309],
        [0.1559, 0.6022, 0.4267, 0.6871, 0.2424]])

In [22]:
g2.ndata['h']

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.9370, 0.8509, 0.3196, 0.1809, 0.7309]])

In [23]:
WORD = 'word'
DOC = 'doc'
DOC_CONTAIN = ('word', 'in', 'doc')

In [24]:
graph_data = {
    DOC_CONTAIN: ([],[])
}

In [25]:
he :dgl.DGLHeteroGraph = dgl.heterograph(graph_data)

In [26]:
he.add_edges([0],[0], data = {'w' : torch.tensor([0.1], dtype=torch.float32)}, etype=DOC_CONTAIN)

In [27]:
he.edges[DOC_CONTAIN]

EdgeSpace(data={'w': tensor([0.1000])})

In [28]:
he.nodes[WORD].data['x'] = torch.randn(size = (1, 5))

In [29]:
he.nodes[DOC]

NodeSpace(data={})

In [30]:
he.nodes[WORD]

NodeSpace(data={'x': tensor([[-1.4668, -1.3288, -1.1736,  0.6882,  0.8185]])})

In [31]:
he.update_all(fn.u_mul_e('x','w', 'm'), fn.mean('m', 'h'), etype=DOC_CONTAIN)

In [32]:
he.nodes[DOC]

NodeSpace(data={'h': tensor([[-0.1467, -0.1329, -0.1174,  0.0688,  0.0818]])})

In [33]:
he.nodes[WORD]

NodeSpace(data={'x': tensor([[-1.4668, -1.3288, -1.1736,  0.6882,  0.8185]])})